# Form implementation generated from reading ui file 'app.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 820)
        MainWindow.setMinimumSize(QtCore.QSize(1200, 820))
        MainWindow.setMaximumSize(QtCore.QSize(1200, 820))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/Logo.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setWindowOpacity(1.0)
        MainWindow.setStyleSheet("background-color: rgb(20, 20, 20);\n"
"font: 57 8pt \"Ubuntu Medium\";\n"
"font-size: 18pt;\n"
"color: rgb(213, 213, 213);")
        MainWindow.setIconSize(QtCore.QSize(50, 50))
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonStyle.ToolButtonIconOnly)
        MainWindow.setDocumentMode(False)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.main_widget = QtWidgets.QWidget(parent=MainWindow)
        self.main_widget.setMinimumSize(QtCore.QSize(1200, 0))
        self.main_widget.setObjectName("main_widget")
        self.MainVideo = QtWidgets.QLabel(parent=self.main_widget)
        self.MainVideo.setGeometry(QtCore.QRect(270, 0, 921, 820))
        self.MainVideo.setMinimumSize(QtCore.QSize(900, 820))
        self.MainVideo.setText("")
        self.MainVideo.setObjectName("MainVideo")
        self.side_bar = QtWidgets.QFrame(parent=self.main_widget)
        self.side_bar.setGeometry(QtCore.QRect(-20, 0, 276, 820))
        self.side_bar.setMinimumSize(QtCore.QSize(0, 820))
        self.side_bar.setMaximumSize(QtCore.QSize(400, 820))
        self.side_bar.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.side_bar.setStyleSheet("border-radius: 17px;\n"
"background-color: rgb(0, 0, 0);")
        self.side_bar.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.side_bar.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.side_bar.setObjectName("side_bar")
        self.home = QtWidgets.QPushButton(parent=self.side_bar)
        self.home.setGeometry(QtCore.QRect(40, 20, 118, 29))
        self.home.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.home.setStyleSheet("QPushButton{\n"
"    border: none;\n"
"    background-color: none;\n"
"}\n"
"QPushButton:hover{\n"
"    color: rgb(255, 255, 255);\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("images/home.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.home.setIcon(icon1)
        self.home.setIconSize(QtCore.QSize(23, 23))
        self.home.setObjectName("home")
        self.support = QtWidgets.QPushButton(parent=self.side_bar)
        self.support.setGeometry(QtCore.QRect(40, 760, 151, 29))
        self.support.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.support.setStyleSheet("QPushButton{\n"
"    border: none;\n"
"    background-color: none;\n"
"}\n"
"QPushButton:hover{\n"
"    color: rgb(255, 255, 255);\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("images/support.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.support.setIcon(icon2)
        self.support.setIconSize(QtCore.QSize(23, 23))
        self.support.setObjectName("support")
        self.settings = QtWidgets.QPushButton(parent=self.side_bar)
        self.settings.setGeometry(QtCore.QRect(40, 60, 144, 29))
        self.settings.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.settings.setStyleSheet("QPushButton{\n"
"    border: none;\n"
"    background-color: none;\n"
"}\n"
"QPushButton:hover{\n"
"    color: rgb(255, 255, 255);\n"
"}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("images/set.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.settings.setIcon(icon3)
        self.settings.setIconSize(QtCore.QSize(23, 23))
        self.settings.setObjectName("settings")
        self.layoutWidget = QtWidgets.QWidget(parent=self.side_bar)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 130, 161, 161))
        self.layoutWidget.setObjectName("layoutWidget")
        self.cameras = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.cameras.setContentsMargins(0, 0, 0, 0)
        self.cameras.setSpacing(0)
        self.cameras.setObjectName("cameras")
        MainWindow.setCentralWidget(self.main_widget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Attention"))
        self.home.setText(_translate("MainWindow", "Главная"))
        self.support.setText(_translate("MainWindow", "Поддержка"))
        self.settings.setText(_translate("MainWindow", "Настройки"))
