# Form implementation generated from reading ui file 'app/ui/warning.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(387, 150)
        font = QtGui.QFont()
        font.setFamily("\"Ubuntu Medium\"")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        Form.setFont(font)
        Form.setStyleSheet("background-color: rgb(20, 20, 20);\n"
"font: 57 8pt \\\"Ubuntu Medium\\\";\n"
"color: rgb(213, 213, 213);\n"
"font-size: 18pt")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.Camera = QtWidgets.QLabel(parent=Form)
        font = QtGui.QFont()
        font.setFamily("\"Ubuntu Medium\"")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.Camera.setFont(font)
        self.Camera.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.Camera.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.Camera.setObjectName("Camera")
        self.verticalLayout.addWidget(self.Camera)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.warning_lable = QtWidgets.QLabel(parent=Form)
        font = QtGui.QFont()
        font.setFamily("\"Ubuntu Medium\"")
        font.setPointSize(30)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.warning_lable.setFont(font)
        self.warning_lable.setStyleSheet("font-size: 30pt")
        self.warning_lable.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.warning_lable.setObjectName("warning_lable")
        self.verticalLayout.addWidget(self.warning_lable)
        self.warning_text_lable = QtWidgets.QLabel(parent=Form)
        font = QtGui.QFont()
        font.setFamily("\"Ubuntu Medium\"")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.warning_text_lable.setFont(font)
        self.warning_text_lable.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.warning_text_lable.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.warning_text_lable.setObjectName("warning_text_lable")
        self.verticalLayout.addWidget(self.warning_text_lable)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.Camera.setText(_translate("Form", "Camera 0"))
        self.warning_lable.setText(_translate("Form", "Warning!"))
        self.warning_text_lable.setText(_translate("Form", "No personal protective equipment!"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
